ecommerce_analytics:
 target: dev
 outputs:
  dev:
    type: bigquery
    method: service-account
    keyfile: /usr/local/airflow/include/gcp/service_account.json
    project: ur_project_identifier
    dataset: ecommerce_analytics
    threads: 1
    timeout_seconds: 300
    location: US